### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by akashnimare** [sideroad/grunt-wpt-page#2]
I have just installed this. How do I run it? node index.js throwing an error

**Comment by sideroad** [comment]
this component should not use directly.
plz use grunt-wpt instead :)

**Comment by akashnimare** [comment]
I have installed grunt-wpt and cloned this repo but I am not able to run it.

**Comment by sideroad** [comment]
Did u get webpagetest API key?
If not yet, plz get the key from page below
http://www.webpagetest.org/getkey.php

After that please set environmental variable as WPT_API_KEY.
then you can execute

**Comment by akashnimare** [comment]
I am not able to get the data. Can you help me out?
Here is my Gruntfile.js
module.exports = function(grunt) {
  grunt.initConfig({
  wpt: {
    options: {
      // locations: ['SanJose_IE9'],
      key: ['A.62ed2309901a4c11f77284b3da0af905']
    },
    sideroad: {
      options: {
        url: [
          'http://akashnimare.in'
        ]
      },
      dest: 'tmp/sideroad/'
    }
  }
});

  grunt.loadNpmTasks('grunt-wpt');
  grunt.registerTask('default', ['wpt']);
};

When I run grunt wpt It did not show any error.

**Comment by akashnimare** [comment]
Yes. I figured it out. I am able to get the data now. How do I get the
pagespeed graphs like speedindex?
